name: add-label-on-pr-created

on:
  pull_request:
    types: [opened, synchronize]

env:
  base_branch: main

jobs:
    add_label:
        runs-on: ubuntu-latest
        permissions:
          pull-requests: write
        steps:
          - name: checkout
            uses: actions/checkout@v3
            with:
              ref: '${{ github.event.pull_request.head.sha }}'
          - name: Fetch base branch
            run: git fetch origin main
          - name: diff
            run: |
              diff_files=$(git diff --name-only HEAD ${base_branch} -- .)
              echo "# diff_files: ${diff_files}"
          - name: echo
            run: |
              echo "diff: ${{ steps.diff.outputs.diff}})"
          - name: add_label
            run: gh pr edit ${{ github.event.number }} --add-label "enhancement"
            env:
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              GH_REPO: ${{ github.repository }}

