name: echo on label added
on:
  pull_request:
    types: [labeled]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: echo
<<<<<<< Updated upstream
        run: echo "${{ github.event.payload.sender.id }}"
=======
        run: echo "$SENDER"
        env:
          SENDER: ${{ github.event.sender.id }}
>>>>>>> Stashed changes
